import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })
import axios from 'axios'
import { useState } from 'react'
import{BsSearch} from 'react-icons/bs'

export default function Home() {

  const[city,setCity] = useState('');
  const[weather,setWeather] = useState({});
  const[loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchWeather = (e)=> {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response)=> {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }
 
  return (
    <>
      <Head>
        <title>Next Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className='text-3xl text-center underline'>Next Weather App</h1>
        <div className='absoulte top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
        <Image src = 'https://images.unsplash.com/photo-1558486012-817176f84c6d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=670&q=80' 
        className='object-cover' layout='fill'/>
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto text white z-10'>
          <form className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
            <div>
              <input 
              onChange = {(e)=> setCity(e.target.value)}
              className='bg-transparent border-none text-white foucs:outline-none text-2xl placeholder:' 
              type="text" 
              placeholder='Search city' />
            </div>
            <button onClick={fetchWeather}><BsSearch size={20} /></button>
          </form>
        </div>
  
    </>
  )
}
